<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerISRZtKc\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerISRZtKc/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerISRZtKc.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerISRZtKc\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerISRZtKc\appAppKernelProdContainer([
    'container.build_hash' => 'ISRZtKc',
    'container.build_id' => '810714aa',
    'container.build_time' => 1680077851,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerISRZtKc');
